[package]
name = "rig-dyn"
authors = ["Gustavo Widman <admin@r3dlust.com>", "Andrei Velikoredchanin <andy@andyhost.world>"]
license = "MIT"
description = "A dynamic client-provider abstraction framework for Rust applications on top of rig-core"
repository = "https://github.com/GustavoWidman/rig-dyn"
homepage = "https://github.com/GustavoWidman/rig-dyn"
version = "1.0.4"
edition = "2024"

[dependencies]
serde_plain = { version = "1.0.2", optional = true }
#serde_plain = { version = "1.0.2" }

anyhow = "1.0.104"

# TODO schemars (in my thesis requires this version)
serde = { version = "1.0.194", optional = true, features = ["derive"] }
#serde = { version = "1.0.229", features = ["derive"] }

# TODO Update branch name when upgrade finish (upgrade started at rig v0.40.0)
rig = "0.41.0"
async-trait = "0.1.91"

[features]
default =  ["dep:serde"]
serde = ["dep:serde", "dep:serde_plain"]

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full"] }
rig-dyn = { path = ".", features = ["serde"] }
serde_plain = "1.0.2"
